/* ES5-only research operations. No external dependencies or newer APIs. */
var SteepLegacy = (function (data) {
  'use strict';
  var records = [], i, j, record;
  for (i=0;i<data.rows.length;i++) { record={demo:true}; for(j=0;j<data.fields.length;j++) record[data.fields[j]]=data.dictionary[j][data.rows[i][j]]; records.push(record); }
  function pad(n){return n<10?'0'+n:String(n);}
  function date(s){var m=/^(\d{4})-(\d{2})-(\d{2})$/.exec(s||'');if(!m)return null;var d=new Date(Date.UTC(+m[1],+m[2]-1,+m[3]));return format(d)===s?d:null;}
  function format(d){return d.getUTCFullYear()+'-'+pad(d.getUTCMonth()+1)+'-'+pad(d.getUTCDate());}
  function period(end,days){var d=date(end);d.setUTCDate(d.getUTCDate()-days+1);return {start:format(d),end:end};}
  function previous(r){var n=Math.round((date(r.end)-date(r.start))/86400000)+1,d=date(r.start);d.setUTCDate(d.getUTCDate()-1);return period(format(d),n);}
  function growth(n,b){return b===0?(n?'New in collected data':'No records'):(n>=b?'+':'')+Math.round((n-b)/b*100)+'%';}
  function filter(rows,f,r){var out=[],k,x,q=(f.q||'').toLowerCase();for(var i=0;i<rows.length;i++){x=rows[i];if(x.published<r.start||x.published>r.end||(!f.allGeo&&x.geo==='unknown'))continue;if(q&&[x.topic,x.text,x.request,x.complaint].join(' ').toLowerCase().indexOf(q)<0)continue;var match=true;for(k=0;k<4;k++){var key=['category','temp','setting','source'][k];if(f[key]&&f[key]!==x[key])match=false;}if(match)out.push(x);}return out;}
  function group(rows,key){var out=[],i,j,x;for(i=0;i<rows.length;i++){x=rows[i][key];if(!x)continue;for(j=0;j<out.length&&out[j].name!==x;j++){}if(j===out.length)out.push({name:x,n:0});out[j].n++;}out.sort(function(a,b){return b.n-a.n;});return out;}
  function ranks(rows,before){var out=group(rows,'topic'),old=group(before,'topic');for(var i=0;i<out.length;i++){out[i].before=0;for(var j=0;j<old.length;j++)if(old[j].name===out[i].name)out[i].before=old[j].n;}return out;}
  function csv(rows,keys){var out=[],i,j,line;function quote(v){return '"'+String(v===undefined?'':v).replace(/"/g,'""')+'"';}line=[];for(j=0;j<keys.length;j++)line.push(quote(keys[j]));out.push(line.join(','));for(i=0;i<rows.length;i++){line=[];for(j=0;j<keys.length;j++)line.push(quote(rows[i][keys[j]]));out.push(line.join(','));}return out.join('\r\n');}
  function parse(text){var rows=[],row=[],cell='',quoted=false,i,c;for(i=0;i<text.length;i++){c=text.charAt(i);if(c==='"'){if(quoted&&text.charAt(i+1)==='"'){cell+='"';i++;}else if(!quoted&&cell!=='')throw Error('Unexpected quote');else quoted=!quoted;}else if(c===','&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text.charAt(i+1)==='\n')i++;row.push(cell);if(row.join('')!=='')rows.push(row);row=[];cell='';}else cell+=c;}if(quoted)throw Error('Unclosed quoted field');row.push(cell);if(row.join('')!=='')rows.push(row);return rows;}
  function trim(s){return String(s||'').replace(/^\s+|\s+$/g,'');}
  function contains(arr,s){for(var i=0;i<arr.length;i++)if(arr[i]===s)return true;return false;}
  function fingerprint(r){return r.published+'|'+trim(r.text).toLowerCase().replace(/\s+/g,' ');}
  function validate(text,existing){if(text.length>500000)throw Error('This tablet importer accepts at most 500 KB of CSV text; split larger files or use the main app.');var rows=parse(text),accepted=[],errors=[],duplicates=0,headers=rows.shift(),ids={},prints={},urls={},i,j,r,k,v; if(!headers||!rows.length)throw Error('Include a header and at least one observation.');headers[0]=headers[0].replace(/^\uFEFF/,'');for(i=0;i<headers.length;i++)for(j=0;j<i;j++)if(headers[i]===headers[j])throw Error('Duplicate headers');for(i=0;i<data.fields.length;i++)if(!contains(headers,data.fields[i]))throw Error('Missing column: '+data.fields[i]);for(i=0;i<existing.length;i++){r=existing[i];ids['$'+r.id]=true;prints['$'+fingerprint(r)]=true;if(r.url)urls['$'+r.url]=true;}for(i=0;i<rows.length;i++){try{if(rows[i].length!==headers.length)throw Error('Column count differs from header');r={demo:false};for(j=0;j<headers.length;j++)r[headers[j]]=trim(rows[i][j]);var required=['id','published','topic','category','temp','setting','source','geo','geoBasis','kind','text'];for(j=0;j<required.length;j++)if(!r[required[j]])throw Error(required[j]+' is required');if(!date(r.published))throw Error('Invalid publication date');var allowed={temp:['Hot','Iced','Mixed'],setting:['At home','Away from home','Unknown / mixed'],geo:['confirmed_us','inferred_us','unknown'],kind:['positive','negative','request','observation']};for(k in allowed)if(Object.prototype.hasOwnProperty.call(allowed,k)&&!contains(allowed[k],r[k]))throw Error('Invalid '+k);if(r.kind==='request'&&!r.request)throw Error('Request text is required');if(r.kind==='negative'&&!r.complaint)throw Error('Complaint text is required');if(r.url&&!/^https?:\/\/[^\s/]+(?:[/?#][^\s]*)?$/i.test(r.url))throw Error('Source URL must be HTTP(S)');if(ids['$'+r.id]||prints['$'+fingerprint(r)]||(r.url&&urls['$'+r.url])){duplicates++;continue;}accepted.push(r);ids['$'+r.id]=true;prints['$'+fingerprint(r)]=true;if(r.url)urls['$'+r.url]=true;}catch(e){errors.push('Row '+(i+2)+': '+e.message);}}return {accepted:accepted,errors:errors,duplicates:duplicates};}
  return {records:records,topics:data.topics,fields:data.fields,anchor:data.anchor,date:date,format:format,period:period,previous:previous,growth:growth,filter:filter,group:group,ranks:ranks,csv:csv,validate:validate,contains:contains,trim:trim};
}(SteepCompatData));
